### ISSUE TITLE
Need for an external server?

### ISSUE THREAD

**Issue by poespas** [jonamat/hetzner-rescaler#2]
Hi there,

We're planning on using this for one of our internal projects, but I couldn't make up from the description if you need to run this on an external server. I'm guessing it is, based on the code I read, but I just wanted to make sure.

Thanks!

**Comment by jonamat** [comment]
Hi! Yes, you need to run the tool from an external machine. It needs very few resources, I run it from a Raspberry from my office and it works great 🙂
